// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Home: typeof import('./.vitepress/vitepress/components/home/index.vue')['default']
    VpDemo: typeof import('./.vitepress/vitepress/components/vp-demo/index.vue')['default']
    VpExample: typeof import('./.vitepress/vitepress/components/vp-demo/vp-example.vue')['default']
    VpSourceCode: typeof import('./.vitepress/vitepress/components/vp-demo/vp-source-code.vue')['default']
  }
}

export {}
